package com.voices.core.common.util

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow

object AppConstants {
    const val AUTH_TIMEOUT_SECONDS = 30L
    const val INPUT_MAX_LINES = 6
    const val DEFAULT_MODEL = "gpt-4o"
    const val DISCLAIMER = "Responses are generated by AI and may contain errors. Verify important information."
}

sealed interface AppResult<out T> {
    data class Success<T>(val data: T) : AppResult<T>
    data class Error(val message: String, val throwable: Throwable? = null) : AppResult<Nothing>
}

object SessionStore {
    private val _userId = MutableStateFlow("guest")
    val userId = _userId.asStateFlow()

    private val _provider = MutableStateFlow("Guest")
    val provider = _provider.asStateFlow()

    private val _defaultModelId = MutableStateFlow(AppConstants.DEFAULT_MODEL)
    val defaultModelId = _defaultModelId.asStateFlow()

    fun signIn(userId: String, provider: String) {
        _userId.value = userId
        _provider.value = provider
    }

    fun setDefaultModel(modelId: String) {
        _defaultModelId.value = modelId
    }
}
